// EU AI label: the European Commission's icons for labelling AI-generated content (Code of
// Practice on Transparency of AI-generated Content, Article 50 AI Act, June 2026) as a layer.
// The twelve icons in assets/ are third-party data, see NOTICE. The plugin rasterises the
// chosen one at the wanted size, places it, and from then on it is an ordinary paint layer:
// the transform tool moves and scales it, the layer row sets opacity and blend, Delete
// removes it, exports flatten it. Adding again replaces the label instead of stacking one.
//
//   panel    "AI label" in the Image pane: label, style, ground, size, position, opacity, Add / Remove
//   actions  Add AI label (last settings), Remove AI label (Plugins menu)
//   commands ailabel.add, ailabel.remove, ailabel.info for scripts and MCP

const LABELS = {
    generated: { file: "ai-generated", label: "AI GENERATED", title: "The picture was generated by AI" },
    modified: { file: "ai-modified", label: "AI MODIFIED", title: "The picture was modified by AI (inpainting, retouch)" },
    mark: { file: "ai", label: "AI mark", title: "The bare AI mark, for small pictures or thumbnails" },
};
// the file name carries the pill's colour: "black" is a black pill with white letters
const STYLES = { dark: { file: "black", label: "White on black", title: "White letters on a black pill" }, light: { file: "white", label: "Dark on white", title: "Dark letters on a white pill" } };
const GROUNDS = { solid: { file: "", label: "Solid" }, translucent: { file: "_transparent", label: "Translucent (50 %)" } };
const ANCHORS = { tl: "Top left", tc: "Top centre", tr: "Top right", ml: "Middle left", mc: "Centre", mr: "Middle right", bl: "Bottom left", bc: "Bottom centre", br: "Bottom right" };
const LAYER_NAME = "AI label";
const DEFAULTS = { label: "generated", style: "dark", ground: "solid", size: 20, sizeMark: 8, anchor: "br", margin: 3, opacity: 100 };
const SOURCE = "https://digital-strategy.ec.europa.eu/en/policies/eu-icons-labelling-ai-generated-content";
const HELP = "The EU icon for AI-generated content, placed as a layer. It is a disclosure mark, not a certificate: it says the picture was generated or modified by AI. Size is a share of the picture's width, the margin a share of its shorter side.";

const svgCache = new Map();          // file stem -> SVG text
const labelLayers = new Map();       // document id -> layer id placed in this session

export function activate(scumble) {
    const { ui } = scumble;

    // ---- settings: the last used values, per user -------------------------------------------------
    function settings(patch) {
        const cur = { ...DEFAULTS, ...(scumble.storage.get() || {}) };
        if (patch) { Object.assign(cur, patch); scumble.storage.set(patch); }
        return cur;
    }
    function normalise(o) {
        const n = { ...o };
        if (!LABELS[n.label]) n.label = DEFAULTS.label;
        if (!STYLES[n.style]) n.style = DEFAULTS.style;
        if (!GROUNDS[n.ground]) n.ground = DEFAULTS.ground;
        if (!ANCHORS[n.anchor]) n.anchor = DEFAULTS.anchor;
        const num = (v, lo, hi, d) => (Number.isFinite(+v) ? Math.min(hi, Math.max(lo, +v)) : d);
        n.size = num(n.size, 1, 100, DEFAULTS.size);
        n.sizeMark = num(n.sizeMark, 1, 100, DEFAULTS.sizeMark);
        n.margin = num(n.margin, 0, 45, DEFAULTS.margin);
        n.opacity = num(n.opacity, 0, 100, DEFAULTS.opacity);
        return n;
    }

    // ---- the icon as pixels ------------------------------------------------------------------------
    async function svgText(stem) {
        if (!svgCache.has(stem)) {
            const r = await fetch(scumble.url(`assets/${stem}.svg`));
            if (!r.ok) throw new Error(`label file ${stem}.svg is missing (${r.status})`);
            svgCache.set(stem, await r.text());
        }
        return svgCache.get(stem);
    }
    /** Rasterise the SVG at `width` pixels; the height follows the viewBox, so the letters keep their proportions (Code of Practice, Measure 1.1). */
    async function rasterise(text, width) {
        const svg = new DOMParser().parseFromString(text, "image/svg+xml").documentElement;
        const vb = (svg.getAttribute("viewBox") || "0 0 1 1").trim().split(/[\s,]+/).map(Number);
        const height = Math.max(1, Math.round(width * vb[3] / vb[2]));
        svg.setAttribute("width", String(width));
        svg.setAttribute("height", String(height));
        const url = URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(svg)], { type: "image/svg+xml" }));
        try {
            const img = await new Promise((resolve, reject) => { const i = new Image(); i.onload = () => resolve(i); i.onerror = () => reject(new Error("the label could not be rendered")); i.src = url; });
            const c = scumble.makeCanvas(width, height);
            c.getContext("2d").drawImage(img, 0, 0, width, height);
            return c;
        } finally {
            URL.revokeObjectURL(url);
        }
    }
    function place(doc, w, h, anchor, marginPct) {
        const m = Math.round(Math.min(doc.width, doc.height) * marginPct / 100);
        const row = anchor[0], col = anchor[1];
        const x = col === "l" ? m : col === "r" ? doc.width - w - m : Math.round((doc.width - w) / 2);
        const y = row === "t" ? m : row === "b" ? doc.height - h - m : Math.round((doc.height - h) / 2);
        return { x, y };
    }
    /** The label layer of a document: the one placed in this session, else a layer with the label's name. */
    function find(doc) {
        const id = labelLayers.get(doc.id);
        const layers = doc.layers();
        return (id && layers.find((l) => l.id === id)) || layers.find((l) => l.name === LAYER_NAME) || null;
    }

    async function add(doc, opts = {}) {
        if (!doc.loaded) throw new Error("Load an image first.");
        const o = normalise({ ...settings(), ...opts });
        const stem = `${LABELS[o.label].file}_${STYLES[o.style].file}${GROUNDS[o.ground].file}`;
        const pct = o.label === "mark" ? (opts.size != null ? o.size : o.sizeMark) : o.size;
        const width = Math.max(8, Math.round(doc.width * pct / 100));
        const canvas = await rasterise(await svgText(stem), width);
        const { x, y } = place(doc, canvas.width, canvas.height, o.anchor, o.margin);
        const old = find(doc);
        if (old) await doc.run("remove_layer", { layer: old.id });
        const layer = doc.addLayer(canvas, { name: LAYER_NAME, x, y });
        if (o.opacity < 100) await doc.run("set_layer", { layer: layer.id, opacity: o.opacity / 100 });
        labelLayers.set(doc.id, layer.id);
        doc.status(`${LABELS[o.label].label} placed ${ANCHORS[o.anchor].toLowerCase()}, ${canvas.width} × ${canvas.height}${old ? ", the previous label replaced" : ""}. It is an ordinary layer now: T moves and scales it.`);
        return { layer: doc.layer(layer.id), file: `${stem}.svg`, replaced: !!old, label: o.label, style: o.style, ground: o.ground, anchor: o.anchor };
    }
    async function remove(doc) {
        const old = find(doc);
        if (!old) { doc.status("No AI label layer in this picture."); return { removed: false }; }
        await doc.run("remove_layer", { layer: old.id });
        labelLayers.delete(doc.id);
        doc.status("AI label removed.");
        return { removed: true, layer: old.id };
    }

    // ---- panel -------------------------------------------------------------------------------------
    scumble.panels.register({
        id: "panel",
        title: "AI label",
        pane: "image",
        open: false,
        build(box, doc) {
            const s = settings();
            const select = (label, title, options, key) => {
                const row = ui.el("div", "scumble-plugin-row");
                row.appendChild(ui.el("span", "scumble-plugin-label", label));
                const sel = document.createElement("select");
                sel.className = "ipc-sel";
                sel.title = title;
                for (const [id, def] of Object.entries(options)) { const o = document.createElement("option"); o.value = id; o.textContent = typeof def === "string" ? def : def.label; if (def.title) o.title = def.title; sel.appendChild(o); }
                sel.value = s[key];
                sel.addEventListener("keydown", (e) => e.stopPropagation());
                sel.addEventListener("change", () => { settings({ [key]: sel.value }); if (key === "label") syncSize(); });
                row.appendChild(sel);
                box.appendChild(row);
                return sel;
            };
            const help = ui.el("div", "shell-help", HELP);
            help.title = `Icons: ${SOURCE} (free to use, no attribution needed; see the plugin's NOTICE)`;
            box.appendChild(help);
            const labelSel = select("Label", "Which icon: the picture was generated, or modified, or the bare mark", LABELS, "label");
            select("Style", "White letters on a black pill, or dark letters on a white one", STYLES, "style");
            select("Ground", "The pill solid, or at half opacity so the picture shows through", GROUNDS, "ground");
            select("Position", "Where the label sits; the margin keeps it off the edge", ANCHORS, "anchor");
            const sizeRow = ui.slider("Size", { min: 1, max: 100, step: 1, value: s.label === "mark" ? s.sizeMark : s.size, unit: " %" }, (v, done) => { if (done) settings({ [labelSel.value === "mark" ? "sizeMark" : "size"]: v }); });
            const sizeInput = sizeRow.querySelector("input"), sizeVal = sizeRow.querySelector(".scumble-plugin-value");
            sizeRow.title = "Width of the label as a share of the picture's width";
            const syncSize = () => { const cur = settings(); const v = labelSel.value === "mark" ? cur.sizeMark : cur.size; sizeInput.value = v; sizeVal.textContent = `${v} %`; };
            box.appendChild(sizeRow);
            const marginRow = ui.slider("Margin", { min: 0, max: 45, step: 1, value: s.margin, unit: " %" }, (v, done) => { if (done) settings({ margin: v }); });
            marginRow.title = "Distance from the edge as a share of the picture's shorter side";
            box.appendChild(marginRow);
            const opacityRow = ui.slider("Opacity", { min: 0, max: 100, step: 1, value: s.opacity, unit: " %" }, (v, done) => { if (done) settings({ opacity: v }); });
            box.appendChild(opacityRow);
            const buttons = ui.el("div", "scumble-plugin-row");
            buttons.appendChild(ui.button("Add label", "Place the label with these settings; an existing label is replaced", () => add(doc).catch((err) => doc.status(String(err.message || err)))));
            buttons.appendChild(ui.button("Remove label", "Remove the label layer", () => remove(doc).catch((err) => doc.status(String(err.message || err)))));
            box.appendChild(buttons);
        },
    });

    // ---- Plugins menu ---------------------------------------------------------------------------------
    scumble.actions.register({ id: "add", label: "Add AI label", run: (doc) => add(doc) });
    scumble.actions.register({ id: "remove", label: "Remove AI label", run: (doc) => remove(doc) });

    // ---- commands ------------------------------------------------------------------------------------
    scumble.commands.register("add", {
        description: "Place the EU AI label as a layer (replaces an existing one). Every parameter defaults to the last setting used in the panel.",
        params: {
            label: { type: "string", description: "generated, modified, or mark (the bare AI mark)", enum: Object.keys(LABELS) },
            style: { type: "string", description: "dark: white letters on a black pill; light: dark letters on white", enum: Object.keys(STYLES) },
            ground: { type: "string", description: "solid, or translucent (the pill at 50 %)", enum: Object.keys(GROUNDS) },
            size: { type: "number", description: "width of the label in percent of the picture's width (1..100; default 20, the mark 8)" },
            anchor: { type: "string", description: "tl, tc, tr, ml, mc, mr, bl, bc, br", enum: Object.keys(ANCHORS) },
            margin: { type: "number", description: "distance from the edge in percent of the picture's shorter side (0..45)" },
            opacity: { type: "number", description: "layer opacity in percent (0..100)" },
        },
        needsImage: true,
        scope: "doc",
        run: (doc, a) => add(doc, a),
    });
    scumble.commands.register("remove", {
        description: "Remove the EU AI label layer from the picture.",
        params: {},
        needsImage: true,
        scope: "doc",
        run: (doc) => remove(doc),
    });
    scumble.commands.register("info", {
        description: "The label variants, positions and the current defaults, plus where the icons come from.",
        params: {},
        scope: "app",
        run: () => ({ labels: Object.fromEntries(Object.entries(LABELS).map(([k, v]) => [k, v.label])), styles: Object.keys(STYLES), grounds: Object.keys(GROUNDS), anchors: ANCHORS, defaults: settings(), source: SOURCE, note: "A disclosure mark, not a certificate of compliance." }),
    });

    scumble.log("loaded");
}

export function deactivate() {
    svgCache.clear();
    labelLayers.clear();
}
