"""Regenerate docs/COMMANDS.md from the running app's command table (see tools/cdp.py).

    python tools/commands_doc.py

Reads `commands.describe()` over DevTools, so plugin commands of the loaded plugins are
listed too (the sample plugin's mean_color with the default set).
"""
import asyncio
import io
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from cdp import session  # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "docs", "COMMANDS.md")

GROUPS = [
    ("App", ["ping", "list_commands", "list_documents", "new_document", "activate_document", "close_document", "list_recipes", "select_recipe", "set_node_params", "list_plugins", "run_action", "filter_types"]),
    ("Document and files", ["status", "new_canvas", "load_image", "add_image_layer", "get_state", "set_status"]),
    ("Selection", ["select_rect", "select_all", "select_none", "select_invert", "select_feather", "select_grow", "select_from_layer", "select_mask", "select_by_text", "select_point"]),
    ("Prompt and generation", ["set_prompt", "set_generation", "set_crop", "set_settings", "upsample_prompt", "generate"]),
    ("Layers", ["list_layers", "set_active_layer", "set_layer", "add_paint_layer", "remove_layer", "duplicate_layer", "merge_down", "move_layer", "flip_layer", "center_layer", "flatten", "cutout_layer"]),
    ("Filters and text", ["add_filter", "set_filter", "add_text", "set_text"]),
    ("History and canvas", ["undo", "redo", "compare", "extend_canvas"]),
    ("Export", ["export", "export_layer", "export_mask", "screenshot"]),
]

INTRO = """# Commands

The command core (`renderer/commands.js`) is the one place every operation of the editor is
reachable from outside the UI: plugins (`scumble.commands.run`), tests (`tools/commands_test.py`),
the devtools console, and in phase 4c the MCP server, which maps every entry below to a tool.
It is the port of the ComfyUI node's bridge table (`js/inpaint_bridge.js`, 46 commands); the
node addressed graph nodes, the app addresses documents (tabs).

```js
const { commands } = await import("./commands.js");   // devtools console of the app
await commands.run("status");
await commands.run("select_rect", { x: 10, y: 10, w: 200, h: 100, doc: 3 });
await commands.call("generate", { timeout: 300 });       // { ok, result } or { ok: false, error }
commands.describe();                                     // this table as data
```

Every command returns JSON and throws with a readable message on failure. Document commands take
`doc` (the id from `list_documents`); without it the active tab is used. Commands marked *image*
need a loaded image. Layers are addressed by id, exact name, a unique part of the name, or
`"active"`. Coordinates are image pixels, origin top left.

This file is generated by `python tools/commands_doc.py` from `commands.describe()` of the
running app; regenerate it after changing the table.
"""

OUTRO = """
## Differences from the node's bridge

- `open_editor`, `close_editor`, `list_nodes`, `ensure_node`, `load_workflow` are gone: the app has
  tabs (`list_documents`, `new_document`, `activate_document`, `close_document`) and recipes
  (`list_recipes`, `select_recipe`) instead of graph nodes and workflows.
- `load_image` and `add_image_layer` take a local `path` as well as a file name in the local
  store / ComfyUI input folder.
- `export`, `export_layer`, `export_mask` take a `path`; without one the native save dialog opens.
- New: `select_mask`, `select_point` (SAM2 in-app), `set_settings`, `set_node_params`,
  `add_paint_layer`, `flatten`, `set_status`, `list_plugins`, `run_action`, `list_commands`.
- `generate` also waits for API-provider runs (no ComfyUI queue to watch there).
"""


def params_table(c):
    ps = c["params"]
    if not ps:
        return "(no parameters)\n"
    lines = ["| param | type | description |", "|---|---|---|"]
    for k, p in ps.items():
        d = p.get("description", "") or ""
        extra = []
        if p.get("required"):
            extra.append("required")
        if p.get("default") is not None and p.get("default") != "":
            extra.append(f"default `{json.dumps(p['default'])}`")
        if p.get("enum"):
            extra.append("one of " + ", ".join(f"`{e}`" for e in p["enum"]))
        if extra:
            d = (d + " " if d else "") + "(" + "; ".join(extra) + ")"
        lines.append(f"| `{k}` | {p.get('type', '')} | {d} |")
    return "\n".join(lines) + "\n"


def render(cmds):
    by = {c["name"]: c for c in cmds}
    listed = {n for _, ns in GROUPS for n in ns}
    groups = list(GROUPS)
    rest = [c["name"] for c in cmds if c["name"] not in listed and not c.get("plugin")]
    if rest:
        groups.append(("Other", rest))
    out = [INTRO]
    for title, names in groups:
        out.append(f"\n## {title}\n")
        for n in names:
            c = by.get(n)
            if not c:
                continue
            tag = " *(app)*" if c["scope"] == "app" else (" *(image)*" if c.get("needsImage") else "")
            out.append(f"\n### `{n}`{tag}\n\n{c['description']}\n\n{params_table(c)}")
    out.append("\n## Plugin commands\n\nPlugins add commands with `scumble.commands.register(name, def)`; the name is prefixed with\n"
               "the plugin id. With the built-in sample plugin loaded:\n")
    for c in cmds:
        if c.get("plugin"):
            out.append(f"\n### `{c['name']}` *(plugin {c['plugin']})*\n\n{c['description']}\n\n{params_table(c)}")
    out.append(OUTRO)
    return "".join(out)


async def run(c):
    cmds = json.loads(await c.eval("(async () => JSON.stringify((await import('./commands.js')).commands.describe()))()"))
    io.open(OUT, "w", encoding="utf-8", newline=chr(10)).write(render(cmds))
    print("wrote docs/COMMANDS.md:", len(cmds), "commands")
    return True


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    asyncio.run(session(run))
